name: 'My Composite Action​'
description: 'This action runs multiple steps'

inputs:
  param1:
    description: 'Parameter based from calling workflow'
runs:
  using: 'composite'​
  steps:
   - run: echo "Step 1 for"
