name: 'My Composite Action​'
description: 'This action runs multiple steps'

inputs:
  param1:
    description: 'Parameter based from calling workflow'
    required: true
runs:
  using: 'composite'​
  steps:
   - run: echo "Step 1 for ${{ inputs.param1 }}"
   - run: echo "Step 2 for ${{ inputs.param1 }}"
