name: 'Caller Workflow​'
on:
  workflow_dispatch:
jobs:
  call-reusable-workflow:​
   runson: ubuntu-latest
   name: composite-workflow
   steps:
    uses: ./.github/workflows/actions/composite-action.yml​
    with:​
      param1: 'Hello, world!'
