name: 'Caller Workflow​'
on:
  workflow_dispatch:
jobs:
  call-reusable-workflow:​
    runs-on: ubuntu-latest
    name: composite-workflow
    steps:
      - id: composite_action
        uses: ./.github/workflows/actions/composite-action.yml​
        with:​
          param1: 'Hello, world!'
